
-- 1. Vue USERS_INFOS (Dépendance pour V_PARDIRECTION)
DROP TABLE IF EXISTS "USERS_INFOS" CASCADE;
DROP VIEW IF EXISTS "USERS_INFOS" CASCADE;
CREATE OR REPLACE VIEW "USERS_INFOS" AS
SELECT A2."USERNAME",A1."MATRICULE",A1."NOM",A1."PRENOM",A1."EMAIL",A1."TEL",A1."CIN",A1."DIRECTION",A1."SERVICE",A1."CD_BUR",A1."BUREAU",A1."PHOTO",A1."FIC_ID",A2."DOMAINE",A1."GRADE",
A1."ETABLISSEMENT",A1."FONCTION",A2."USER_TYPE",A1."ADD_DATE",A2."STATUT",A2."APP_VALID",A2."ACT_TOKEN",A2."RES_TOKEN", A3."ID_SESSION" AS "SESS_TOKEN" 
FROM "PERSONNEL" A1
LEFT JOIN "GRH_USERS" A2 ON A1."USERNAME" = A2."USERNAME"
LEFT JOIN "USER_SESSION" A3 ON A2."USERNAME" = A3."USERNAME";

-- 2. Vue V_PARDIRECTION
DROP TABLE IF EXISTS "V_PARDIRECTION" CASCADE;
DROP VIEW IF EXISTS "V_PARDIRECTION" CASCADE;
CREATE OR REPLACE VIEW "V_PARDIRECTION" AS
SELECT "DIRECTION", COUNT(*) AS "NOMBRE" FROM "USERS_INFOS"
GROUP BY "DIRECTION" ORDER BY "NOMBRE" DESC;

-- 3. Vue V_PRIVILEGE
DROP TABLE IF EXISTS "V_PRIVILEGE" CASCADE;
DROP VIEW IF EXISTS "V_PRIVILEGE" CASCADE;
CREATE OR REPLACE VIEW "V_PRIVILEGE" AS
SELECT PV."ID",PV."CD_APP",AP."SLUG",PV."PRIVILEGE",AP."APP_NOM",PV."DESCRIPTION",PV."PRIV_TYPE" AS "TYPE",
PV."NIVEAU_ROLE" AS "ROLE", PV."NIVEAU_ACCES" AS "ACCES"
FROM "APP_PRIVILEGE" PV LEFT JOIN "APP_LIST" AP ON PV."CD_APP" = AP."CD_APP";

-- 4. Vue USER_DATAS
DROP TABLE IF EXISTS "USER_DATAS" CASCADE;
DROP VIEW IF EXISTS "USER_DATAS" CASCADE;
CREATE OR REPLACE VIEW "USER_DATAS" AS
SELECT A2."USERNAME",A1."MATRICULE",A1."NOM",A1."PRENOM",A1."EMAIL",A1."TEL",A1."CIN",A1."DIRECTION",A3."NOM" AS "DIR_NAME", A1."SERVICE",A1."CD_BUR",A1."BUREAU",A1."PHOTO",A1."FIC_ID",A2."DOMAINE",A1."GRADE",
A1."ETABLISSEMENT",A1."FONCTION",A2."USER_TYPE",A1."ADD_DATE",A2."STATUT",A2."APP_VALID"
FROM "PERSONNEL" A1
LEFT JOIN "GRH_USERS" A2 ON A1."USERNAME" = A2."USERNAME"
LEFT JOIN "DIRECTIONS" A3 ON A1."DIRECTION" = A3."ABREV";

-- 5. Vue USERAPPS
DROP TABLE IF EXISTS "USERAPPS" CASCADE;
DROP VIEW IF EXISTS "USERAPPS" CASCADE;
CREATE OR REPLACE VIEW "USERAPPS" AS
SELECT A0."ID",A0."USERNAME",A0."EMAIL",A0."MATRICULE",A3."NOM",A3."PRENOM",A0."CD_ACCESS" AS "MPASS",A1."CD_APP",A2."APP_NOM",A2."SLUG",A2."DESCRIPTION",A2."STATUS",A1."ACTIF",A1."PROFILE",
    A1."ROLE_1",A1."ROLE_2",A1."ROLE_3",A1."ROLE_4",A2."URL",A2."LOGO",A3."CD_BUR",A3."SERVICE",A2."DEFAULT_APP" AS "DEFAPP"
  FROM "GRH_USERS" A0
    LEFT JOIN "PERSONNEL" A3 ON A0."USERNAME" = A3."USERNAME"
    LEFT JOIN "USER_APP" A1 ON A0."USERNAME" = A1."USERNAME"
    LEFT JOIN "APP_LIST" A2 ON A1."CD_APP" = A2."CD_APP";

-- 6. Vue APPS_INFO
DROP TABLE IF EXISTS "APPS_INFO" CASCADE;
DROP VIEW IF EXISTS "APPS_INFO" CASCADE;
CREATE OR REPLACE VIEW "APPS_INFO" AS
SELECT UA."USERNAME",UA."CD_APP",AL."SLUG",AL."URL",AL."STATUS",AL."LOGO",AL."APP_NOM",AL."DESCRIPTION"
FROM "USER_APP" UA
LEFT JOIN "APP_LIST" AL ON UA."CD_APP" = AL."CD_APP";
