DROP TABLE IF EXISTS "AFFECTATIONS";
CREATE TABLE "AFFECTATIONS" (
  "ID" NUMERIC,
  "MATRICULE" NUMERIC,
  "DIRECTION" VARCHAR(50),
  "SERVICE" VARCHAR(20),
  "DATE_DEBUT" TIMESTAMP,
  "DATE_FIN" TIMESTAMP,
  "FONCTION" VARCHAR(100),
  "OBSERVATION" VARCHAR(500),
  "DATE_MODIF" TIMESTAMP,
  "OPER" NUMERIC
);

DROP TABLE IF EXISTS "API_ACCESS";
CREATE TABLE "API_ACCESS" (
  "ID" INTEGER,
  "KEY" VARCHAR(40),
  "ALL_ACCESS" INTEGER,
  "CONTROLLER" VARCHAR(250),
  "DATE_CREATED" TIMESTAMP,
  "DATE_MODIFIED" TIMESTAMP
);

DROP TABLE IF EXISTS "API_KEYS";
CREATE TABLE "API_KEYS" (
  "ID" INTEGER,
  "USER_ID" INTEGER,
  "TAG" VARCHAR(100),
  "SECRETS" VARCHAR(40),
  "LEVELS" INTEGER,
  "IGNORE_LIMITS" INTEGER,
  "IS_PRIVATE_KEY" INTEGER,
  "IP_ADDRESSES" VARCHAR(250),
  "DATE_CREATED" TIMESTAMP
);

DROP TABLE IF EXISTS "API_KEYS_PROD";
CREATE TABLE "API_KEYS_PROD" (
  "ID" INTEGER,
  "USER_ID" INTEGER,
  "TAG" VARCHAR(150),
  "SECRETS" VARCHAR(40),
  "LEVELS" INTEGER,
  "IGNORE_LIMITS" INTEGER,
  "IS_PRIVATE_KEY" INTEGER,
  "IP_ADDRESSES" VARCHAR(250),
  "DATE_CREATED" TIMESTAMP
);

DROP TABLE IF EXISTS "API_LISTE";
CREATE TABLE "API_LISTE" (
  "ID" INTEGER,
  "API_NOM" VARCHAR(200),
  "API_DESC" VARCHAR(250),
  "METHODE" VARCHAR(20),
  "URL" VARCHAR(500),
  "REPONSE" VARCHAR(30),
  "INPUT_DATA" VARCHAR(4000),
  "OUTPUT_DATA" VARCHAR(4000),
  "INPUT_EX" VARCHAR(4000),
  "OUTPUT_EX" VARCHAR(4000),
  "API_INFOS" VARCHAR(4000),
  "UNAUTHORIZED" VARCHAR(4000),
  "FORBIDDEN" VARCHAR(4000),
  "CATEGORIE" VARCHAR(200),
  "CONTROLLER" VARCHAR(250)
);

DROP TABLE IF EXISTS "API_MEMBERS";
CREATE TABLE "API_MEMBERS" (
  "USER_ID" INTEGER,
  "NAME" VARCHAR(250),
  "EMAIL" VARCHAR(100),
  "KEY_ID" INTEGER,
  "API_ALLOW" VARCHAR(2000)
);

DROP TABLE IF EXISTS "APPS_ADMIN";
CREATE TABLE "APPS_ADMIN" (
  "ID" NUMERIC,
  "NOM" VARCHAR(100),
  "SERVICE" VARCHAR(150),
  "CD_BUR" VARCHAR(50),
  "EMAIL" VARCHAR(100),
  "TEL" VARCHAR(20),
  "DESCRIPTION" VARCHAR(500),
  "TYPE" VARCHAR(20),
  "UXID" VARCHAR(100),
  "CREATED_AT" TIMESTAMP,
  "UPDATED_AT" TIMESTAMP,
  "IS_ACTIVE" INTEGER
);

DROP TABLE IF EXISTS "APPS_INFO";
CREATE TABLE "APPS_INFO" (
  "USERNAME" VARCHAR(100),
  "CD_APP" VARCHAR(20),
  "SLUG" VARCHAR(70),
  "URL" VARCHAR(250),
  "STATUS" VARCHAR(50),
  "LOGO" VARCHAR(100),
  "APP_NOM" VARCHAR(100),
  "DESCRIPTION" VARCHAR(500)
);

DROP TABLE IF EXISTS "APP_LIST";
CREATE TABLE "APP_LIST" (
  "ID" NUMERIC,
  "APP_NOM" VARCHAR(100),
  "DESCRIPTION" VARCHAR(500),
  "SLUG" VARCHAR(70),
  "STATUS" VARCHAR(50),
  "LOGO" VARCHAR(100),
  "URL" VARCHAR(250),
  "CD_APP" VARCHAR(20),
  "DEFAULT_APP" VARCHAR(20),
  "DEFAULT_PRIV" VARCHAR(20),
  "CREATED_AT" TIMESTAMP,
  "UPDATED_AT" TIMESTAMP,
  "UXID" VARCHAR(100)
);

DROP TABLE IF EXISTS "APP_PRIVILEGE";
CREATE TABLE "APP_PRIVILEGE" (
  "ID" NUMERIC,
  "CD_APP" VARCHAR(20),
  "PRIVILEGE" VARCHAR(150),
  "DESCRIPTION" VARCHAR(500),
  "PRIV_TYPE" VARCHAR(50),
  "NIVEAU_ROLE" NUMERIC,
  "NIVEAU_ACCES" NUMERIC,
  "LEVEL1" NUMERIC,
  "LEVEL2" NUMERIC,
  "UXID" VARCHAR(100),
  "CREATED_AT" TIMESTAMP,
  "UPDATED_AT" TIMESTAMP
);

DROP TABLE IF EXISTS "DIRECTIONS";
CREATE TABLE "DIRECTIONS" (
  "ID" NUMERIC,
  "NOM" VARCHAR(100),
  "ABREV" VARCHAR(20),
  "CODE_DIR" NUMERIC,
  "UXID" VARCHAR(100),
  "CREATED_AT" TIMESTAMP,
  "UPDATED_AT" TIMESTAMP,
  "IS_ACTIVE" INTEGER
);

DROP TABLE IF EXISTS "DIRECTIONS_T";
CREATE TABLE "DIRECTIONS_T" (
  "ID" NUMERIC,
  "NOM" VARCHAR(100),
  "ABREV" VARCHAR(20),
  "CODE_DIR" NUMERIC,
  "DIR_REF" VARCHAR(20),
  "DIR_CODE" VARCHAR(50)
);

DROP TABLE IF EXISTS "DIR_CORRESP";
CREATE TABLE "DIR_CORRESP" (
  "ID" NUMERIC,
  "DIR_REF" VARCHAR(20),
  "DIR_CODE" VARCHAR(50)
);

DROP TABLE IF EXISTS "GRH_USERS";
CREATE TABLE "GRH_USERS" (
  "ID" INTEGER,
  "MATRICULE" NUMERIC,
  "EMAIL" VARCHAR(100),
  "CD_ACCESS" VARCHAR(500),
  "SESS_TOKEN" VARCHAR(500),
  "RES_TOKEN" VARCHAR(500),
  "ACT_TOKEN" VARCHAR(500),
  "DATE_ADD" TIMESTAMP,
  "STATUT" VARCHAR(20),
  "USER_TYPE" VARCHAR(50),
  "USR_TOKEN" VARCHAR(500),
  "USERNAME" VARCHAR(100),
  "DOMAINE" VARCHAR(20),
  "APP_VALID" VARCHAR(20),
  "UPDATED_AT" TIMESTAMP,
  "UXID" VARCHAR(100)
);

DROP TABLE IF EXISTS "PERSONNEL";
CREATE TABLE "PERSONNEL" (
  "ID" INTEGER,
  "MATRICULE" NUMERIC,
  "NOM" VARCHAR(100),
  "PRENOM" VARCHAR(100),
  "DIRECTION" VARCHAR(50),
  "SERVICE" VARCHAR(50),
  "CD_BUR" VARCHAR(20),
  "CIN" VARCHAR(20),
  "FONCTION" VARCHAR(100),
  "BUREAU" VARCHAR(100),
  "PHOTO" VARCHAR(100),
  "FIC_ID" VARCHAR(100),
  "CODE_X" VARCHAR(100),
  "ADRESSE" VARCHAR(500),
  "ADD_DATE" TIMESTAMP,
  "BIRTH_DATE" TIMESTAMP,
  "EMAIL" VARCHAR(100),
  "TEL" VARCHAR(20),
  "FONC_STATUT" VARCHAR(100),
  "STAT_MATRI" VARCHAR(100),
  "ETABLISSEMENT" VARCHAR(100),
  "GRADE" VARCHAR(50),
  "USERNAME" VARCHAR(100),
  "UPDATED_AT" TIMESTAMP,
  "UXID" VARCHAR(100),
  "USER_UXID" VARCHAR(100)
);

DROP TABLE IF EXISTS "PERSONNEL_T";
CREATE TABLE "PERSONNEL_T" (
  "ID" INTEGER,
  "MATRICULE" NUMERIC,
  "NOM" VARCHAR(100),
  "PRENOM" VARCHAR(100),
  "DIRECTION" VARCHAR(50),
  "SERVICE" VARCHAR(50),
  "CD_BUR" VARCHAR(20),
  "CIN" VARCHAR(20),
  "FONCTION" VARCHAR(100),
  "BUREAU" VARCHAR(100),
  "PHOTO" VARCHAR(100),
  "FIC_ID" VARCHAR(100),
  "CODE_X" VARCHAR(100),
  "ADRESSE" VARCHAR(500),
  "ADD_DATE" TIMESTAMP,
  "BIRTH_DATE" TIMESTAMP,
  "EMAIL" VARCHAR(100),
  "TEL" VARCHAR(20),
  "FONC_STATUT" VARCHAR(100),
  "STAT_MATRI" VARCHAR(100),
  "ETABLISSEMENT" VARCHAR(100),
  "GRADE" VARCHAR(50),
  "USERNAME" VARCHAR(100),
  "PERS_CODE" INTEGER,
  "DIR_ID" NUMERIC,
  "SERV_ID" NUMERIC
);

DROP TABLE IF EXISTS "PERS_CORRESP";
CREATE TABLE "PERS_CORRESP" (
  "ID" INTEGER,
  "PERS_CODE" INTEGER
);

DROP TABLE IF EXISTS "PRT_DIRECTIONS";
CREATE TABLE "PRT_DIRECTIONS" (
  "ID_DIR" INTEGER,
  "DIR_REF" INTEGER,
  "CORRESP_T" INTEGER,
  "DIR_NOM" VARCHAR(250),
  "ABREV" VARCHAR(250),
  "CD_DIR" VARCHAR(50),
  "DIR_DESC" VARCHAR(500),
  "DIR_STATUT" INTEGER,
  "DIR_CODE" VARCHAR(150)
);

DROP TABLE IF EXISTS "RH_SITUATIONS";
CREATE TABLE "RH_SITUATIONS" (
  "PERS_CODE" INTEGER,
  "LIEU_CODE" INTEGER,
  "FONC_REF" VARCHAR(60),
  "DIR_REF" VARCHAR(20),
  "SDIR_REF" VARCHAR(20),
  "DIV_REF" VARCHAR(20),
  "PFONC_NUMDECISION" VARCHAR(150),
  "PFONC_DATE" TIMESTAMP,
  "PFONC_ANNEE" INTEGER,
  "STAT_CODE" INTEGER,
  "COR_CODE" INTEGER,
  "GRAD_CODE" INTEGER,
  "PAVANC_NUMARRETE" VARCHAR(150),
  "PAVANC_DATEARRETE" TIMESTAMP,
  "IND_CODE" INTEGER,
  "CATEG_CODE" INTEGER,
  "DIP_CODE" INTEGER,
  "FORMA_CODE" INTEGER,
  "PRECLAS_ANNEE" NUMERIC,
  "PRECLAS_ANNEEDIPL" NUMERIC,
  "SCOR_CODE" NUMERIC,
  "SITU_DATEPRISESERVICE" TIMESTAMP,
  "SITU_DATECORPS" TIMESTAMP,
  "SITU_DATEGRADE" TIMESTAMP,
  "PFONC_DATEPRISESERVICE" TIMESTAMP,
  "SITU_DATECAT" TIMESTAMP,
  "CC_CODE" VARCHAR(4),
  "MODIF_DATE" TIMESTAMP,
  "BUD_CODE" VARCHAR(25),
  "CODE_MODE" INTEGER,
  "PFONC_NOTESERV" VARCHAR(150),
  "PFONC_DATENOTESERV" TIMESTAMP,
  "CADRE" VARCHAR(5),
  "CADRE_RDR" VARCHAR(2)
);

DROP TABLE IF EXISTS "RH_SITUATIONS_PORTAL";
CREATE TABLE "RH_SITUATIONS_PORTAL" (
  "PERS_CODE" INTEGER,
  "PERS_MAT" NUMERIC,
  "PERS_NOM" VARCHAR(50),
  "PERS_PRENOMS" VARCHAR(50),
  "PERS_CIN" BIGINT,
  "DIR_REF" VARCHAR(20),
  "SDIR_REF" VARCHAR(20),
  "FONC_REF" VARCHAR(60),
  "PERS_STATUT" VARCHAR(50)
);

DROP TABLE IF EXISTS "SERVICES";
CREATE TABLE "SERVICES" (
  "ID" NUMERIC,
  "NOM" VARCHAR(100),
  "DIR" VARCHAR(50),
  "ABREV" VARCHAR(100),
  "CD_BUR" VARCHAR(20),
  "LIEU_BUREAU" VARCHAR(100),
  "ADRESSE" VARCHAR(250),
  "MAIL" VARCHAR(100),
  "TEL" VARCHAR(20),
  "TEL_2" VARCHAR(20),
  "IS_ACTIVE" INTEGER,
  "UXID" VARCHAR(100),
  "CREATED_AT" TIMESTAMP,
  "UPDATED_AT" TIMESTAMP,
  "DIR_UXID" VARCHAR(100)
);

DROP TABLE IF EXISTS "SERVICES_T";
CREATE TABLE "SERVICES_T" (
  "ID" NUMERIC,
  "NOM" VARCHAR(100),
  "DIR" VARCHAR(50),
  "ABREV" VARCHAR(100),
  "CD_BUR" VARCHAR(20),
  "LIEU_BUREAU" VARCHAR(100),
  "ADRESSE" VARCHAR(250),
  "MAIL" VARCHAR(100),
  "TEL" VARCHAR(20),
  "TEL_2" VARCHAR(20),
  "DIR_ID" NUMERIC,
  "SDIR_REF" VARCHAR(20),
  "SDIR_CODE" VARCHAR(50)
);

DROP TABLE IF EXISTS "SERV_CORRESP";
CREATE TABLE "SERV_CORRESP" (
  "ID" NUMERIC,
  "DIR_ID" NUMERIC,
  "SDIR_REF" VARCHAR(20),
  "SDIR_CODE" VARCHAR(50)
);

DROP TABLE IF EXISTS "TEST_DATE";
CREATE TABLE "TEST_DATE" (
  "DATE_JOUR" TIMESTAMP,
  "STRING_2" VARCHAR(100),
  "STRING_1" VARCHAR(250),
  "UXID" VARCHAR(100),
  "UPDATED_AT" TIMESTAMP,
  "ID" INTEGER,
  "TEST" INTEGER
);

DROP TABLE IF EXISTS "USERAPPS";
CREATE TABLE "USERAPPS" (
  "ID" INTEGER,
  "USERNAME" VARCHAR(100),
  "EMAIL" VARCHAR(100),
  "MATRICULE" NUMERIC,
  "NOM" VARCHAR(100),
  "PRENOM" VARCHAR(100),
  "MPASS" VARCHAR(500),
  "CD_APP" VARCHAR(20),
  "APP_NOM" VARCHAR(100),
  "SLUG" VARCHAR(70),
  "DESCRIPTION" VARCHAR(500),
  "STATUS" VARCHAR(50),
  "ACTIF" INTEGER,
  "PROFILE" VARCHAR(50),
  "ROLE_1" VARCHAR(50),
  "ROLE_2" VARCHAR(50),
  "ROLE_3" VARCHAR(50),
  "ROLE_4" VARCHAR(50),
  "URL" VARCHAR(250),
  "LOGO" VARCHAR(100),
  "CD_BUR" VARCHAR(20),
  "SERVICE" VARCHAR(50),
  "DEFAPP" VARCHAR(20)
);

DROP TABLE IF EXISTS "USERS_INFOS";
CREATE TABLE "USERS_INFOS" (
  "USERNAME" VARCHAR(100),
  "MATRICULE" NUMERIC,
  "NOM" VARCHAR(100),
  "PRENOM" VARCHAR(100),
  "EMAIL" VARCHAR(100),
  "TEL" VARCHAR(20),
  "CIN" VARCHAR(20),
  "DIRECTION" VARCHAR(50),
  "SERVICE" VARCHAR(50),
  "CD_BUR" VARCHAR(20),
  "BUREAU" VARCHAR(100),
  "PHOTO" VARCHAR(100),
  "FIC_ID" VARCHAR(100),
  "DOMAINE" VARCHAR(20),
  "GRADE" VARCHAR(50),
  "ETABLISSEMENT" VARCHAR(100),
  "FONCTION" VARCHAR(100),
  "USER_TYPE" VARCHAR(50),
  "ADD_DATE" TIMESTAMP,
  "STATUT" VARCHAR(20),
  "APP_VALID" VARCHAR(20),
  "ACT_TOKEN" VARCHAR(500),
  "RES_TOKEN" VARCHAR(500),
  "SESS_TOKEN" VARCHAR(500)
);

DROP TABLE IF EXISTS "USER_ACCESS";
CREATE TABLE "USER_ACCESS" (
  "ID" INTEGER,
  "ACCESS" VARCHAR(250),
  "ABREV" VARCHAR(100),
  "UXID" VARCHAR(100),
  "CREATED_AT" TIMESTAMP,
  "UPDATED_AT" TIMESTAMP,
  "USER_UXID" VARCHAR(100),
  "IS_ACTIVE" NUMERIC
);

DROP TABLE IF EXISTS "USER_ACCESS_LIST";
CREATE TABLE "USER_ACCESS_LIST" (
  "ID" INTEGER,
  "USER_ID" INTEGER,
  "ACCESS_ID" INTEGER,
  "CREATED_AT" TIMESTAMP,
  "UPDATED_AT" TIMESTAMP,
  "ADMIN_ID" INTEGER
);

DROP TABLE IF EXISTS "USER_APP";
CREATE TABLE "USER_APP" (
  "ID" NUMERIC,
  "USERNAME" VARCHAR(100),
  "CD_APP" VARCHAR(20),
  "ROLE_1" VARCHAR(50),
  "ROLE_2" VARCHAR(50),
  "ROLE_3" VARCHAR(50),
  "ROLE_4" VARCHAR(50),
  "ACTIF" INTEGER,
  "PROFILE" VARCHAR(50),
  "DATE_AJOUT" TIMESTAMP,
  "VALIDATEUR" NUMERIC,
  "UXID" VARCHAR(100),
  "UPDATED_AT" TIMESTAMP
);

DROP TABLE IF EXISTS "USER_DATAS";
CREATE TABLE "USER_DATAS" (
  "USERNAME" VARCHAR(100),
  "MATRICULE" NUMERIC,
  "NOM" VARCHAR(100),
  "PRENOM" VARCHAR(100),
  "EMAIL" VARCHAR(100),
  "TEL" VARCHAR(20),
  "CIN" VARCHAR(20),
  "DIRECTION" VARCHAR(50),
  "DIR_NAME" VARCHAR(100),
  "SERVICE" VARCHAR(50),
  "CD_BUR" VARCHAR(20),
  "BUREAU" VARCHAR(100),
  "PHOTO" VARCHAR(100),
  "FIC_ID" VARCHAR(100),
  "DOMAINE" VARCHAR(20),
  "GRADE" VARCHAR(50),
  "ETABLISSEMENT" VARCHAR(100),
  "FONCTION" VARCHAR(100),
  "USER_TYPE" VARCHAR(50),
  "ADD_DATE" TIMESTAMP,
  "STATUT" VARCHAR(20),
  "APP_VALID" VARCHAR(20)
);

DROP TABLE IF EXISTS "USER_GRADES";
CREATE TABLE "USER_GRADES" (
  "ID" INTEGER,
  "GRADE" VARCHAR(250),
  "ABREV" VARCHAR(50),
  "UXID" VARCHAR(100),
  "CREATED_AT" TIMESTAMP,
  "UPDATED_AT" TIMESTAMP,
  "IS_ACTIVE" INTEGER
);

DROP TABLE IF EXISTS "USER_SESSION";
CREATE TABLE "USER_SESSION" (
  "ID" NUMERIC,
  "MATRICULE" NUMERIC,
  "ID_SESSION" VARCHAR(500),
  "DEBUT" TIMESTAMP,
  "FIN" TIMESTAMP,
  "EXPIRE" NUMERIC,
  "USER_AGENT" VARCHAR(600),
  "IP_ADDR" VARCHAR(20),
  "EMAIL" VARCHAR(100),
  "USERNAME" VARCHAR(100),
  "ID_APP" NUMERIC
);

DROP TABLE IF EXISTS "V_PARDIRECTION";
CREATE TABLE "V_PARDIRECTION" (
  "DIRECTION" VARCHAR(50),
  "NOMBRE" NUMERIC
);

DROP TABLE IF EXISTS "V_PRIVILEGE";
CREATE TABLE "V_PRIVILEGE" (
  "ID" NUMERIC,
  "CD_APP" VARCHAR(20),
  "SLUG" VARCHAR(70),
  "PRIVILEGE" VARCHAR(150),
  "APP_NOM" VARCHAR(100),
  "DESCRIPTION" VARCHAR(500),
  "TYPE" VARCHAR(50),
  "ROLE" NUMERIC,
  "ACCES" NUMERIC
);

